name: Daily Foot Traffic Update

on:
  schedule:
    # Run at 7 AM Melbourne time (9 PM UTC previous day)
    - cron: '0 21 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update-traffic-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run traffic processing script with OAuth
      run: |
        python process_traffic_oauth.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add hourly_foot_traffic.parquet token.pickle
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update foot traffic data - $(date +'%Y-%m-%d')" && git push)
